stages:
  - build
  - deploy

default:
  image: registry.inf.ethz.ch/isg/rhel8-ci:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^v2$/
    - if: $FORCE_DEPLOY
      when: always
    - when: never

build:
  stage: build
  image: node:21-alpine3.18
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths: [node_modules/]
  artifacts:
    when: on_success
    expire_in: 1 week
    paths: [out/]
  before_script:
    # Install git inside the node:alpine image so we can fetch submodules
    - apk add --no-cache git openssh
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - npm ci
  script:
    - npm run build

deploy_prod:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'v2'
  before_script:
    - |-
      mkdir -pm 700 ~/.ssh
      base64 -d "${CI_KNOWN_HOSTS}" >~/.ssh/known_hosts
      eval $(ssh-agent -s)
      base64 -d "${CI_KEY}" | ssh-add -
      git config --global user.name "${GITLAB_USER_NAME}"
      git config --global user.email "${GITLAB_USER_EMAIL}"
      git config --global safe.directory '*'
  script:
    - |-
      git clone --single-branch --branch release --depth 1 git@${CI_SERVER_HOST}:/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}.git build-release
      rsync -av --delete --exclude '.git/' out/ build-release/
      cd build-release
      git add --all
      git commit --allow-empty --message "GitLab Runner Push from ${CI_PROJECT_URL}, commit ${CI_COMMIT_SHA}"
      git push
