export const blogData = [
  { week: "W4", title: "Visual Debugging", slug: "visual-debugging", author: "Junzhe Tai" },
  { week: "W4", title: "In Situ Visualization", slug: "in-situ-visualization", author: "Alexander Eggerth" },
  { week: "W5", title: "Structured Editors", slug: "structured-editors", author: "Julian Kalitzke" },
  { week: "W5", title: "Task Decomposition", slug: "task-decomposition", author: "Leroy Borgeaud dit Avocat" },
  { week: "W6", title: "Sketching and Diagramming", slug: "sketching-and-diagramming", author: "Yuchen Zhong" },
  { week: "W6", title: "Programming by Demonstration", slug: "programming-by-demonstration", author: "Aimen Dokhane" },
  { week: "W7", title: "Meta Code", slug: "meta-code", author: "Olivia Furrer" },
  { week: "W7", title: "Computational Notebooks", slug: "computational-notebooks", author: "Rohan Chilukuri" },
  { week: "W8", title: "Version Management", slug: "version-management", author: "Veit Billinger" },
  { week: "W8", title: "Real-time Collaborative Editing", slug: "real-time-collaborative-editing", author: "Mark Sosman" },
  { week: "W9", title: "Programming Interactive Articles", slug: "programming-interactive-articles", author: "Dominique Buob" },
  { week: "W9", title: "Programming Scenes", slug: "programming-scenes", author: "Omar Hammoud" },
  { week: "W10", title: "Developer Community", slug: "developer-community", author: "David Märki" },
  { week: "W11", title: "Code Clustering", slug: "code-clustering", author: "Melanie Woon" },
  { week: "W11", title: "Code Tutorials", slug: "code-tutorials", author: "Alexandre Ballenghien" },
  { week: "W12", title: "No Code Environment", slug: "no-code-environment", author: "Tim Kaltenbrunner" },
  { week: "W12", title: "Accessibility", slug: "accessibility", author: "Jan Blum" },
];
