export const blogData = [
  { week: "W4", title: "Visual Debugging", slug: "visual-debugging", author: "Junzhe Tai", desc: "Log-it and Ply: Visual tools for debugging and learning from professional webpages." },
  { week: "W4", title: "In Situ Visualization", slug: "in-situ-visualization", author: "Alexander Eggerth", desc: "Augmenting code with inline visualizations to aid program understanding." },
  { week: "W5", title: "Structured Editors", slug: "structured-editors", author: "Julian Kalitzke", desc: "Exploring Hazelnut and Sandblocks for structured editing and interaction." },
  { week: "W5", title: "Task Decomposition", slug: "task-decomposition", author: "Leroy Borgeaud dit Avocat", desc: "Improving AI-assisted data analysis through interactive task decomposition." },
  { week: "W6", title: "Sketching and Diagramming", slug: "sketching-and-diagramming", author: "Yuchen Zhong", desc: "Code Shaping and Chisel: Iterative code editing with free-form sketching." },
  { week: "W6", title: "Programming by Demonstration", slug: "programming-by-demonstration", author: "Aimen Dokhane", desc: "Helena and ReCode: Transforming code by example and execution history." },
  { week: "W7", title: "Meta Code", slug: "meta-code", author: "Olivia Furrer", desc: "Torii and Meta-manager: Organizing tutorials and collecting meta information." },
  { week: "W7", title: "Computational Notebooks", slug: "computational-notebooks", author: "Rohan Chilukuri", desc: "Pagebreaks and mage: Fluid moves between code and graphical work in notebooks." },
  { week: "W8", title: "Version Management", slug: "version-management", author: "Veit Billinger", desc: "Verdant and Code Gathering: Managing messes and foraging past choices." },
  { week: "W8", title: "Real-time Collaborative Editing", slug: "real-time-collaborative-editing", author: "Mark Sosman", desc: "Collabode and Coprompt: Supporting real-time collaboration and prompt sharing." },
  { week: "W9", title: "Programming Interactive Articles", slug: "programming-interactive-articles", author: "Dominique Buob", desc: "CrossData and Idyll: Authoring and publishing interactive data documents." },
  { week: "W9", title: "Programming Scenes", slug: "programming-scenes", author: "Omar Hammoud", desc: "FlowMatic and Worldsmith: Immersive authoring and generative world building." },
  { week: "W10", title: "Developer Community", slug: "developer-community", author: "David Märki", desc: "Social Q&A and Tidy Tuesday: Community engagement and practice for data scientists." },
  { week: "W11", title: "Code Clustering", slug: "code-clustering", author: "Melanie Woon", desc: "VizProg and CPVis: Visualizing student progress and collaborative programming." },
  { week: "W11", title: "Code Tutorials", slug: "code-tutorials", author: "Alexandre Ballenghien", desc: "Lead-and-Reveal and Porta: Profiling tutorials and enhancing learning with AI." },
  { week: "W12", title: "No Code Environment", slug: "no-code-environment", author: "Tim Kaltenbrunner", desc: "Scratch and Co-ML: Programming for all and collaborative machine learning." },
  { week: "W12", title: "Accessibility", slug: "accessibility", author: "Jan Blum", desc: "Tangiblegrid and Axnav: Tangible layout design and replaying accessibility tests." },
];
